AY2324S1-CS2103T-W09-2/tp

- docs/UserGuide.md
Add UG for Contacts Management, test MarkBind formatting
> Update UG from Draft UG

- docs/UserGuide.md
Change intro to freelancebuddy
Reformat several parts of the UG
Comment out several portions we are not using for now
> Reformat several parts of UG for markbind render

- docs/DeveloperGuide.md
Change Value proposition for grammar
Update user stories for FreelanceBuddy
Add UC1 - Get help
Add UC2 - Navigating tabs
Organise and add NFRs related to FreelanceBuddy
Change glossary related to FreelanceBuddy
> Update DG - Value propositions, User stories, UC1- help, UC2 - tabs, NFRs, Glossary

- docs/UserGuide.md
- docs/index.md
Formatting change, put delete command info in an admonition box
Several spelling errors
Update index.md to FreelanceBuddy
> Minor change to UG contacts management

- docs/DeveloperGuide.md
- Minor edits 
- Set list needing at least one entry as the preconditions for non add entry use cases
> User Case update

- src/main/java/seedu/address/ui/MainWindow2.java
- src/main/java/seedu/address/ui/UiManager.java
- src/main/java/seedu/address/ui/tab/ContactsTab.java
- src/main/java/seedu/address/ui/tab/EventsTab.java
- src/main/java/seedu/address/ui/tab/FinanceTab.java
- src/main/resources/view/ContactsTab.fxml
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/DashboardTab.fxml
- src/main/resources/view/EventsTab.fxml
- src/main/resources/view/FinanceTab.fxml
- src/main/resources/view/MainWindow2.fxml
Create temporary branch for this until the Tab structure is finalized
> Implement Tabs

- src/main/java/seedu/address/logic/commands/finance/AddCommissionCommand.java
- src/main/java/seedu/address/logic/commands/finance/DeleteFinanceCommand.java
- src/main/java/seedu/address/logic/commands/finance/ListFinanceCommand.java
- src/main/java/seedu/address/logic/parser/finance/AddCommissionParser.java
- src/main/java/seedu/address/logic/parser/finance/DeleteFinanceParser.java
- src/main/java/seedu/address/logic/parser/finance/ListFinanceParser.java
- src/main/java/seedu/address/model/finance/Amount.java
- src/main/java/seedu/address/model/finance/Commission.java
- src/main/java/seedu/address/model/finance/Description.java
- src/test/java/seedu/address/logic/commands/finance/AddCommissionCommandTest.java
- src/test/java/seedu/address/logic/commands/finance/DeleteFinanceCommandTest.java
- src/test/java/seedu/address/logic/commands/finance/ListFinanceCommandTest.java
- src/test/java/seedu/address/logic/parser/finance/AddCommissionParserTest.java
- src/test/java/seedu/address/logic/parser/finance/DeleteFinanceParserTest.java
- src/test/java/seedu/address/logic/parser/finance/ListFinanceParserTest.java
- src/test/java/seedu/address/model/finance/AmountTest.java
- src/test/java/seedu/address/model/finance/CommissionTest.java
- src/test/java/seedu/address/model/finance/DescriptionTest.java
- src/test/java/seedu/address/testutil/CommissionBuilder.java
- src/test/java/seedu/address/testutil/TypicalCommissions.java
Also add CommisionBuilder and TypicalCommissions in TestUtil.
> Add Finance models, commands and parser and their test cases

- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/logic/parser/contacts/AddContactCommandParser.java
- src/main/java/seedu/address/logic/parser/contacts/ContactParser.java
- src/main/java/seedu/address/logic/parser/contacts/DeleteCommandParser.java
- src/main/java/seedu/address/logic/parser/contacts/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/contacts/FindCommandParser.java
- src/main/java/seedu/address/model/person/Address.java
- src/main/java/seedu/address/model/person/Company.java
- src/main/java/seedu/address/model/person/Name.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/person/Phone.java
- src/main/java/seedu/address/model/person/TelegramName.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/PersonListCard.fxml
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/logic/parser/ContactParserTest.java
- src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
- src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
- src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
ContactParser can now accept optional arguments
Note: Still cannot add contact because storage has not been implemented in full (WIP)
> Implement Contact Parsing. Refactor classes to command parser.

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/parser/contacts/AddContactCommandParser.java
- src/main/java/seedu/address/logic/parser/contacts/ContactParser.java
- src/main/java/seedu/address/logic/parser/contacts/DeleteContactCommandParser.java
- src/main/java/seedu/address/logic/parser/contacts/EditContactCommandParser.java
- src/main/java/seedu/address/logic/parser/contacts/FindContactCommandParser.java
- src/main/java/seedu/address/model/person/Phone.java
- src/main/java/seedu/address/model/person/TelegramName.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/PersonListCard.fxml
- src/test/java/seedu/address/logic/parser/DeleteContactCommandParserTest.java
- src/test/java/seedu/address/logic/parser/FindContactCommandParserTest.java
- src/test/java/seedu/address/model/person/EventNameContainsKeywordsPredicateTest.java
- src/test/java/seedu/address/model/person/EventNameTest.java
Change phone validation regex
Change add/delete message to include company and telegram name
> Add TelegramName to person card

- src/main/java/seedu/address/model/person/Phone.java
- src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
- src/test/java/seedu/address/model/person/NameTest.java
> Refactor Class Names

- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/finance/AddCommissionCommandTest.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/model/event/EventTest.java
* Integrate test with classes from master branch
> Integrate test case with new class and constructor

- src/main/java/seedu/address/model/event/Event.java
- src/main/java/seedu/address/model/event/EventList.java
- src/test/java/seedu/address/logic/commands/events/AddEventCommandIntegrationTest.java
- src/test/java/seedu/address/logic/commands/events/AddEventCommandTest.java
- src/test/java/seedu/address/logic/commands/events/DeleteEventCommandTest.java
- src/test/java/seedu/address/testutil/EventBuilder.java
- src/test/java/seedu/address/testutil/TypicalEvents.java
- src/test/java/seedu/address/testutil/TypicalIndexes.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
* Implement some test case for event command (WIP)
* Add toString() to Event class
> (WIP) Add some test case to event commands

- src/main/java/seedu/address/logic/commands/events/AddEventCommand.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/event/Event.java
- src/main/java/seedu/address/model/person/UniquePersonList.java
- src/test/java/seedu/address/logic/commands/contact/AddContactCommandTest.java
- src/test/java/seedu/address/logic/commands/events/AddEventCommandTest.java
- src/test/java/seedu/address/logic/commands/finance/AddCommissionCommandTest.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- src/test/java/seedu/address/logic/parser/events/EventParserTest.java
- src/test/java/seedu/address/testutil/EventUtil.java
* ParserUtilTest cover all new parser
* EventPaserTest
* AddEventCommandTest
* Other files due to change in Model
> Add remaining testcase for Event parsing

- src/main/java/seedu/address/logic/commands/events/AddEventCommand.java
- src/main/java/seedu/address/logic/parser/events/AddEventCommandParser.java
- src/main/java/seedu/address/model/event/Event.java
- src/test/java/seedu/address/logic/parser/events/AddEventCommandParserTest.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
* Fix AddEventCommandParserTest
* Create new dummy person builder
> Fix test case

- src/main/java/seedu/address/logic/parser/finance/FinanceParser.java
- src/main/java/seedu/address/ui/FinanceCard.java
- src/test/java/seedu/address/logic/parser/finance/FinanceParserTest.java
- Also Fix bug where exit and help commands did not work in the Finance tab
> Add color to differentiate between Finances

- docs/DeveloperGuide.md
- docs/diagrams/StorageClassDiagram.puml
* Update UML diagram 
* Refer to docs/diagrams/StorageClassDiagram.uml to view changes
* Update details for Storage Component
> Update UML and details for Storage component in DG

- _markbind/logs/markbind-2023-10-27.log
- docs/DeveloperGuide.md
- docs/diagrams/BetterModelClassDiagramAddressBook.puml
- docs/diagrams/BetterModelClassDiagramEventsBook.puml
- docs/diagrams/BetterModelClassDiagramFinancesBook.puml
- docs/diagrams/ModelClassDiagram.puml
* Modify ModelClassDiagram
* Added BetterModelClassDiagramEventsBook and BetterModelClassDiagramFinancesBook
> Adapt Developer's Guide-Model Component to FreelanceBuddy

- src/main/java/seedu/address/model/util/EventBuilder.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/ui/FinanceCard.java
- src/main/resources/view/CommandBox.fxml
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/FinanceListPanel.fxml
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/MainWindow2.fxml
- src/main/resources/view/PersonListCard.fxml
- src/main/resources/view/PersonListPanel.fxml
- src/main/resources/view/ResultDisplay.fxml
- src/main/resources/view/StatusBarFooter.fxml
* Change UI appearance
* Modify sample data such that upon first open, events will always have pre-filled data (future data).
> Change UI appearance and modify sample data

- src/main/java/seedu/address/model/util/EventBuilder.java
- src/main/resources/view/DarkTheme.css
CSS: change background colour of empty cells to match background, so empty cells are not shown
EventBuilder: Error where timeEnd was put as timeStart
> Bug fix for UI and EventBuilder

- src/main/java/seedu/address/logic/commands/events/ClearEventsCommand.java
- src/main/java/seedu/address/logic/commands/finance/ClearFinanceCommand.java
- src/main/java/seedu/address/logic/parser/events/EventParser.java
- src/main/java/seedu/address/logic/parser/finance/FinanceParser.java
- src/main/java/seedu/address/model/event/EventClientContainsKeywordsPredicate.java
- src/main/java/seedu/address/model/person/Name.java
- src/test/java/seedu/address/logic/commands/events/ClearEventsCommandTest.java
- src/test/java/seedu/address/logic/commands/finance/ClearFinanceCommandTest.java
- src/test/java/seedu/address/logic/parser/events/EventParserTest.java
- src/test/java/seedu/address/logic/parser/finance/FinanceParserTest.java
* Implement clear command for all tabs
* Bug fix for `filter-c` to ignore case
> Implement clear command

- src/main/java/seedu/address/model/person/Phone.java
* Change the message constraint as message constraint was outdated
Closes #185
> Fix bug: Wrong message constraint for Phone Number

- docs/UserGuide.md
- Resolve #220 
- Resolve #210 
- Resolve #171 
- Resolve #170 
- Potentially resolved #192
- I just reordered the warnings for filter commands
- Unsure on how to resolve this properly
> Bug fix for user guide

- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/events/EditEventCommand.java
- src/main/java/seedu/address/logic/commands/finance/EditFinanceCommand.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/logic/parser/events/EditEventCommandParser.java
- src/main/java/seedu/address/logic/parser/finance/EditFinanceCommandParser.java
- src/main/java/seedu/address/model/finance/Commission.java
- src/main/java/seedu/address/model/finance/Expense.java
- src/main/java/seedu/address/model/finance/Finance.java
- src/main/java/seedu/address/storage/finance/JsonAdaptedCommission.java
- src/main/java/seedu/address/ui/HelpWindow.java
- src/test/java/seedu/address/model/finance/ExpenseTest.java
- src/test/java/seedu/address/storage/finance/JsonAdaptedCommissionTest.java
- src/test/java/seedu/address/testutil/ExpenseBuilder.java
- Fix not being able to edit multiple clients for events
- Fix not being able to edit finances with no clients
- Fix the link in the help window
> Bug fix for edit commands and help window

- docs/team/dloh2236.md
* Added some features I did (for first draft)
> Update PPP for dloh2236

- docs/UserGuide.md
[HALFWAY] Add command summary/ToC for each management.
> Update User Guide and Fix UG Bugs

- docs/UserGuide.md
Solves issue #221 
Explains issue #204 #201 #183 #166 
These are features flaws, do not close
> Documentation bugfixes

- src/main/java/seedu/address/ui/tab/ContactsTab.java
- src/main/java/seedu/address/ui/tab/EventsTab.java
- src/main/java/seedu/address/ui/tab/FinanceTab.java
- src/test/java/seedu/address/commons/util/JsonUtilTest.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/parser/events/EventParserTest.java
- src/test/java/seedu/address/model/person/UniquePersonListTest.java
- src/test/java/seedu/address/storage/events/JsonSerializableEventsBookTest.java
- src/test/java/seedu/address/storage/finance/JsonSerializableFinancesBookTest.java
Removed todos.
Removed orphan print statement.
> Code cleanup

- docs/DeveloperGuide.md
* Update Manual Testing for Contacts
* Update Use Case for Contacts
> Update DG Manual Testing and Use Case
